/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWebhookRouteImport } from './routes/_authenticated/webhook'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCompanySlugIndexRouteImport } from './routes/_authenticated/$companySlug/index'
import { Route as ApiPublicCeletusWebhookRouteImport } from './routes/api/public/celetus-webhook'
import { Route as AuthenticatedCompanySlugWebhookRouteImport } from './routes/_authenticated/$companySlug/webhook'
import { Route as AuthenticatedCompanySlugSettingsRouteImport } from './routes/_authenticated/$companySlug/settings'
import { Route as AuthenticatedCompanySlugProductsRouteImport } from './routes/_authenticated/$companySlug/products'
import { Route as AuthenticatedCompanySlugDashboardRouteImport } from './routes/_authenticated/$companySlug/dashboard'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWebhookRoute = AuthenticatedWebhookRouteImport.update({
  id: '/webhook',
  path: '/webhook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanySlugIndexRoute =
  AuthenticatedCompanySlugIndexRouteImport.update({
    id: '/$companySlug/',
    path: '/$companySlug/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCeletusWebhookRoute = ApiPublicCeletusWebhookRouteImport.update({
  id: '/api/public/celetus-webhook',
  path: '/api/public/celetus-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompanySlugWebhookRoute =
  AuthenticatedCompanySlugWebhookRouteImport.update({
    id: '/$companySlug/webhook',
    path: '/$companySlug/webhook',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompanySlugSettingsRoute =
  AuthenticatedCompanySlugSettingsRouteImport.update({
    id: '/$companySlug/settings',
    path: '/$companySlug/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompanySlugProductsRoute =
  AuthenticatedCompanySlugProductsRouteImport.update({
    id: '/$companySlug/products',
    path: '/$companySlug/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompanySlugDashboardRoute =
  AuthenticatedCompanySlugDashboardRouteImport.update({
    id: '/$companySlug/dashboard',
    path: '/$companySlug/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/products': typeof AuthenticatedProductsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/webhook': typeof AuthenticatedWebhookRoute
  '/$companySlug/dashboard': typeof AuthenticatedCompanySlugDashboardRoute
  '/$companySlug/products': typeof AuthenticatedCompanySlugProductsRoute
  '/$companySlug/settings': typeof AuthenticatedCompanySlugSettingsRoute
  '/$companySlug/webhook': typeof AuthenticatedCompanySlugWebhookRoute
  '/api/public/celetus-webhook': typeof ApiPublicCeletusWebhookRoute
  '/$companySlug/': typeof AuthenticatedCompanySlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/products': typeof AuthenticatedProductsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/webhook': typeof AuthenticatedWebhookRoute
  '/$companySlug/dashboard': typeof AuthenticatedCompanySlugDashboardRoute
  '/$companySlug/products': typeof AuthenticatedCompanySlugProductsRoute
  '/$companySlug/settings': typeof AuthenticatedCompanySlugSettingsRoute
  '/$companySlug/webhook': typeof AuthenticatedCompanySlugWebhookRoute
  '/api/public/celetus-webhook': typeof ApiPublicCeletusWebhookRoute
  '/$companySlug': typeof AuthenticatedCompanySlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/webhook': typeof AuthenticatedWebhookRoute
  '/_authenticated/$companySlug/dashboard': typeof AuthenticatedCompanySlugDashboardRoute
  '/_authenticated/$companySlug/products': typeof AuthenticatedCompanySlugProductsRoute
  '/_authenticated/$companySlug/settings': typeof AuthenticatedCompanySlugSettingsRoute
  '/_authenticated/$companySlug/webhook': typeof AuthenticatedCompanySlugWebhookRoute
  '/api/public/celetus-webhook': typeof ApiPublicCeletusWebhookRoute
  '/_authenticated/$companySlug/': typeof AuthenticatedCompanySlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/products'
    | '/settings'
    | '/webhook'
    | '/$companySlug/dashboard'
    | '/$companySlug/products'
    | '/$companySlug/settings'
    | '/$companySlug/webhook'
    | '/api/public/celetus-webhook'
    | '/$companySlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/products'
    | '/settings'
    | '/webhook'
    | '/$companySlug/dashboard'
    | '/$companySlug/products'
    | '/$companySlug/settings'
    | '/$companySlug/webhook'
    | '/api/public/celetus-webhook'
    | '/$companySlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/products'
    | '/_authenticated/settings'
    | '/_authenticated/webhook'
    | '/_authenticated/$companySlug/dashboard'
    | '/_authenticated/$companySlug/products'
    | '/_authenticated/$companySlug/settings'
    | '/_authenticated/$companySlug/webhook'
    | '/api/public/celetus-webhook'
    | '/_authenticated/$companySlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCeletusWebhookRoute: typeof ApiPublicCeletusWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/webhook': {
      id: '/_authenticated/webhook'
      path: '/webhook'
      fullPath: '/webhook'
      preLoaderRoute: typeof AuthenticatedWebhookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$companySlug/': {
      id: '/_authenticated/$companySlug/'
      path: '/$companySlug'
      fullPath: '/$companySlug/'
      preLoaderRoute: typeof AuthenticatedCompanySlugIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/celetus-webhook': {
      id: '/api/public/celetus-webhook'
      path: '/api/public/celetus-webhook'
      fullPath: '/api/public/celetus-webhook'
      preLoaderRoute: typeof ApiPublicCeletusWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$companySlug/webhook': {
      id: '/_authenticated/$companySlug/webhook'
      path: '/$companySlug/webhook'
      fullPath: '/$companySlug/webhook'
      preLoaderRoute: typeof AuthenticatedCompanySlugWebhookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$companySlug/settings': {
      id: '/_authenticated/$companySlug/settings'
      path: '/$companySlug/settings'
      fullPath: '/$companySlug/settings'
      preLoaderRoute: typeof AuthenticatedCompanySlugSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$companySlug/products': {
      id: '/_authenticated/$companySlug/products'
      path: '/$companySlug/products'
      fullPath: '/$companySlug/products'
      preLoaderRoute: typeof AuthenticatedCompanySlugProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$companySlug/dashboard': {
      id: '/_authenticated/$companySlug/dashboard'
      path: '/$companySlug/dashboard'
      fullPath: '/$companySlug/dashboard'
      preLoaderRoute: typeof AuthenticatedCompanySlugDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWebhookRoute: typeof AuthenticatedWebhookRoute
  AuthenticatedCompanySlugDashboardRoute: typeof AuthenticatedCompanySlugDashboardRoute
  AuthenticatedCompanySlugProductsRoute: typeof AuthenticatedCompanySlugProductsRoute
  AuthenticatedCompanySlugSettingsRoute: typeof AuthenticatedCompanySlugSettingsRoute
  AuthenticatedCompanySlugWebhookRoute: typeof AuthenticatedCompanySlugWebhookRoute
  AuthenticatedCompanySlugIndexRoute: typeof AuthenticatedCompanySlugIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWebhookRoute: AuthenticatedWebhookRoute,
  AuthenticatedCompanySlugDashboardRoute:
    AuthenticatedCompanySlugDashboardRoute,
  AuthenticatedCompanySlugProductsRoute: AuthenticatedCompanySlugProductsRoute,
  AuthenticatedCompanySlugSettingsRoute: AuthenticatedCompanySlugSettingsRoute,
  AuthenticatedCompanySlugWebhookRoute: AuthenticatedCompanySlugWebhookRoute,
  AuthenticatedCompanySlugIndexRoute: AuthenticatedCompanySlugIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCeletusWebhookRoute: ApiPublicCeletusWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
