ALTER TABLE public.monthly_tax_settings
  ADD COLUMN IF NOT EXISTS monthly_expenses NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS company_cash_rate NUMERIC(6,4) NOT NULL DEFAULT 0.10,
  ADD COLUMN IF NOT EXISTS partner_1_name TEXT NOT NULL DEFAULT 'Rodrigo',
  ADD COLUMN IF NOT EXISTS partner_1_rate NUMERIC(6,4) NOT NULL DEFAULT 0.35,
  ADD COLUMN IF NOT EXISTS partner_2_name TEXT NOT NULL DEFAULT 'Marcos',
  ADD COLUMN IF NOT EXISTS partner_2_rate NUMERIC(6,4) NOT NULL DEFAULT 0.65;
